[package]
name = "tetr_online"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
rand = "0.8.5"
leafwing-input-manager = "0.9.1"
array2d = "0.3.0"
bevy_asset_loader = "0.15.0"

[dependencies.bevy]
version = "0.10.1"
default-features = false
features = [
    "bevy_sprite",
    "bevy_render",
    "bevy_audio",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
    "bevy_core_pipeline",
    "vorbis",
    "png"
]

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[profile.release]
# optimize for size
opt-level = 'z'
#lto = "thin"